### PR TITLE
Start window invisible on Windows

### PR DESCRIPTION
**Pull request by kchibisov**
It should make our Windows window creation follow other backends and start window invisible. However it was started visible on purpose, so I'm not sure whether it breaks something or not.

Could Windows folks test whether it breaks anything for them or not?

### CODE REVIEW

**Comment by cole-h** [comment]
I don't see any issues on my Windows VM: `Version 1909 (OS Build 18363.592)`.

**Comment by chrisduerr** [comment]
@cole-h If you change [this line](https://github.com/alacritty/alacritty/blob/5f6a4334eae864f55a7bb075783c5d00f9beab0e/alacritty/src/window.rs#L144) to unwrap, does it crash for you?

**Comment by kchibisov** [comment]
I'm not sure about a CHANGELOG for this thing. Do we need something for this change?

**Comment by chrisduerr** [comment]
> I'm not sure about a CHANGELOG for this thing. Do we need something for this change?

I don't think we should, we just change some internal thing for consistency. So this will probably be fine. I didn't notice any difference myself.

**Pull request merged**
