### PR TITLE
Relax horizontal scrolling

### PR DESCRIPTION
**Pull request by kchibisov**
This should trigger horizontal scrolling with touchpads only when the amount of pixel change towards x is highter than towards y.

### CODE REVIEW

**Review by chrisduerr — APPROVED** [review]

**Comment by kchibisov** [comment]
I've changed the logic to be based on angles, and not just higher.

**Review by chrisduerr — APPROVED** [review]

**Comment by nixpulvis** [comment]
I was expecting to see a 45 degree line, or am I confused?

**Comment by kchibisov** [comment]
>I was expecting to see a 45 degree line, or am I confused?

You don't really want to see horizontal scrolling in terminal in any form unless you actually try to do that.

**Comment by nixpulvis** [comment]
Interesting. I'll have to play with it in a bit. This is exciting to see though!

**Pull request merged**
