### PR TITLE
macOS dock & menu items

### PR DESCRIPTION
**Pull request by ZirixCZ**
This patch adds support for dock items on MacOS, which allows further management of the application on the Apple platform.

### New features
Ability to create a new OS window through the dock

- [ ] Implement NSApplicationDelegate <a href="https://developer.apple.com/documentation/appkit/nsapplicationdelegate">apple docs</a>, <a href="https://docs.rs/cocoa/0.24.1/cocoa/appkit/trait.NSApplication.html">cocoa docs</a>
- [ ] Set <a href="https://docs.rs/cocoa/0.24.1/cocoa/appkit/enum.NSApplicationActivationPolicy.html">application activation policies</a>
- [ ] Implement <a href="https://docs.rs/cocoa/0.24.1/cocoa/appkit/trait.NSMenu.html">NSmenu</a> and <a href="https://docs.rs/cocoa/0.24.1/cocoa/appkit/trait.NSMenuItem.html">NSMenuItem</a>

For more info refer to this opened issue https://github.com/alacritty/alacritty/issues/6391
For reference, this is how WezTerm had implemented it https://github.com/wez/wezterm/blob/c38d160918596364ac8ce786fcf8bf1f44adbb56/window/src/os/macos/app.rs (line 154, application_dock_menu)

### CODE REVIEW

**Comment by ZirixCZ** [comment]
- [ ] Implement NSApplicationDelegate <a href="https://developer.apple.com/documentation/appkit/nsapplicationdelegate">apple docs</a>, <a href="https://docs.rs/cocoa/0.24.1/cocoa/appkit/trait.NSApplication.html">cocoa docs</a>
- [ ] Set <a href="https://docs.rs/cocoa/0.24.1/cocoa/appkit/enum.NSApplicationActivationPolicy.html">application activation policies</a>
- [ ] Implement <a href="https://docs.rs/cocoa/0.24.1/cocoa/appkit/trait.NSMenu.html">NSmenu</a> and <a href="https://docs.rs/cocoa/0.24.1/cocoa/appkit/trait.NSMenuItem.html">NSMenuItem</a>

For more info refer to this opened issue https://github.com/alacritty/alacritty/issues/6391

**Review by chrisduerr — CHANGES_REQUESTED** [review]
This should be integrated into Winit.

**Comment by chrisduerr** [comment]
> Hence I would like to ask where in the project is the logic concerning winit and where should the code in this PR be.

https://github.com/rust-windowing/winit

**Comment by chrisduerr** [comment]
Closing since an API for this should really be exposed by winit, rather than hacking it into Alacritty.

**Comment by TimTheBig** [comment]
This has been added to winit in the pull "feat: added MacOS menu" [#1583](https://github.com/rust-windowing/winit/pull/1583)

**Pull request closed without merging**
