### PR TITLE
Colored underline

### PR DESCRIPTION
**Pull request by kchibisov**
--
Just testing perf of this, since I think it could be done way better than original approach.

### CODE REVIEW

**Comment by kchibisov** [comment]
@perfbot

**Comment by kchibisov** [comment]
@perfbot

**Comment by kchibisov** [comment]
I've tried various approaches and it seems like it's always slower. The closest thing is when no dynamic memory is in use. But that it'll increase runtime memory... Though if we could shorten our pointer it'll help.

picture

**Comment by chrisduerr** [comment]
@perfbot (Just testing something)

**Comment by chrisduerr** [comment]
@perfbot (Just testing something)

**Pull request closed without merging**
