### PR TITLE
Remove obsolete ansicode.txt file

### PR DESCRIPTION
**Pull request by BuriedInTheGround**

### CODE REVIEW

**Review by kchibisov — APPROVED** [review]
I still sort of think that this file shouldn't exist, because the docs are present at https://invisible-island.net/xterm/ctlseqs/ctlseqs.html.

**Comment by BuriedInTheGround** [comment]
I have to say that I don't disagree. The file is historically present in the repo, but documentation on ANSI sequences is easily found online. Personally, it makes no difference to me whether the file stays or not, I leave that decision to the maintainers of alacritty.

**Comment by kchibisov** [comment]
The thing is that this file is basically an original pdf beeing rewritten, we do provide links to the docs that should be used on the wiki. The links on the wiki page provide the extensive reference https://github.com/alacritty/alacritty/wiki/ANSI-References .

It just I know that none of the maintainers use this file. But I'd rather handle the deletion separately with @chrisduerr .

**Comment by BuriedInTheGround** [comment]
@kchibisov if you agree, I'll delete the file and update the PR.

**Comment by kchibisov** [comment]
aye, you can delete the file.

**Review by chrisduerr — APPROVED** [review]

**Pull request merged**
