### PR TITLE
Add Simplified Chinese introductions

### PR DESCRIPTION
**Pull request by AStogov**
## New files
1. README_zh-CN.md: __Introduction of Alacritty in Simplified Chinese__
2. INSTALL_zh-CN.md: __Help to install in Simplified Chinese__
3. docs/features_zh-CN.md: __Introduction of features in Simplified Chinese__

## Changed files:
1. README.md: __Added a language entry of Simplified Chinese__

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
I have no interest maintaining anything other than English documentation.

**Comment by AStogov** [comment]
> I have no interest maintaining anything other than English documentation.

Yes I see, this project only serves your "interest".

**Comment by kchibisov** [comment]
The main issue with any sorts of translations is that they get desyncronized with the languages developers write documentations in.

This is also hard to review, since you need to find 'other' people(besides you) to cross validate what you've provided.

Don't get us wrong, given that native language for maintainers is not even English in the first place.

**Comment by AStogov** [comment]
> The main issue with any sorts of translations is that they get desyncronized with the languages developers write documentations in.
> 
> This is also hard to review, since you need to find 'other' people(besides you) to cross validate what you've provided.
> 
> Don't get us wrong, given that native language for maintainers is not even English in the first place.

Indeed. Thanks for your reply🎉

**Pull request closed without merging**
