### PR TITLE
Update a few dependencies

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by kchibisov** [comment]
Nice. Could you also bump winit and those macOS packages https://github.com/alacritty/alacritty/blob/840cb1b93a68389fab63e5a8f94cdaa2d607d1c3/font/Cargo.toml#L20 while we're at it?

**Comment by Eijebong** [comment]
I don't have a way to test that the update builds, that's why I left them alone

**Comment by kchibisov** [comment]
I mean CI will build it for you.

**Comment by Eijebong** [comment]
Actually it would dupe a few mac related dependencies to upgrade them.

**Comment by Eijebong** [comment]
```
    Updating crates.io index
      Adding core-foundation v0.7.0
      Adding core-foundation-sys v0.7.0
      Adding core-graphics v0.19.0
    Updating core-text v13.3.2 -> v15.0.0
```

**Comment by kchibisov** [comment]
Well,  you can at least bump winit and it's good to go.

**Pull request merged**
