### PR TITLE
Derive `Clone` for `EventLoopSender`

### PR DESCRIPTION
**Pull request by HyperHamster**
`.spawn()` consumes `EventLoop` making it impossible to acquire more senders by calling `.channel()` after the fact. It is possible to produce all the senders you would need in advance by calling `.channel()` multiple times before calling `.spawn()` but this is very unidiomatic and would both pollute the namespace and hinder readability. I am proposing this change under the assumption that it is generally always expected that Sender (new)types implement `Clone`.

### CODE REVIEW

**Comment by chrisduerr** [comment]
Curious about your goal with this? Are you trying to write to the PTY from multiple different threads? How are you synchronizing this?

**Comment by HyperHamster** [comment]
This pull request doesn't affect synchronization since you're using `std::sync::mpsc::Sender` and `polling::Poller` which both already correctly handle synchronization across threads internally; Artificially limiting the conditions under which `EventLoopSender` may be cloned does nothing to protect users from synchronization issues.

But to sate your curiosity I have implemented an Alacritty front-end in Discord via a [Serenity](https://github.com/serenity-rs/serenity) bot. This bot handles input from multiple sources and potentially users at once including both raw bytestring input and pre-programmed byte sequences bound to [clickable buttons](https://discord.com/developers/docs/interactions/message-components#buttons) for keys like `Esc` and `Backspace` that cannot be easily typed into a text field by users. The Serenity standard framework is heavily `async` so I rely on being able to clone the `EventLoopSender` (previously `mio_extras::channel::Sender` in `0.19`) associated with a given terminal session as necessary when I need to send input from the `tokio` runtime to the separate thread(s) running the Alacritty event loop providing the bot with terminal emulation.

The code for this is currently private as it in no way secure and only meant to played with in a private server with friends; That and I have no interest in hosting/maintaining a public bot.

**Comment by kchibisov** [comment]
I wonder whether we can plug our event loop into async loop in such a case btw?

I'm fine with `Clone`, but maybe we can do it a bit better? Like inserting `poller` into async runtime should be fine, probably?

**Review by kchibisov — APPROVED** [review]

**Review by chrisduerr — APPROVED** [review]
Just needs rebase.

**Pull request merged**
