### PR TITLE
Tell what to do with unused keys

### PR DESCRIPTION
**Pull request by kchibisov**
--

¯\_(ツ)_/¯

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
I don't think anyone is having struggles understanding that part? This just bloats up the message bar.

**Comment by kchibisov** [comment]
>I don't think anyone is having struggles understanding that part? This just bloats up the message bar.

There were a few where people were not sure what to do. Some thought that they haven't added something.

**Comment by chrisduerr** [comment]
> There were a few where people were not sure what to do. Some thought that they haven't added something.

Yeah but I think that's mostly confusion about getting an error when they didn't before, not that they're confused about what to do.

**Comment by chrisduerr** [comment]
> it's a message bar you see pretty rare

Especially right now people are **constantly** running into this. That's the only reason why you changed it in the first place. So our goal should be to actually be constructive.

**Comment by kchibisov** [comment]
yeah, and there's clear a "don't know what to do" situation, because they never get a warning for unused key before.

**Pull request closed without merging**
