### PR TITLE
Fix: Always check X11 dpr is sane

### PR DESCRIPTION
**Pull request by JOT85**
Following discussion of #5536, this only contains the fix to the X11 bug.

Only update and receive dpr values through `update_dpr` and `get_dpr`, `update_dpr` method always perform the X11 dpr sanity check. Previsouly, this check was performed on startup but not when moving between screens. This means that when moving to a screen with an insane dpr value, it would be used, but when started on that screen, it would not.

### CODE REVIEW

**Review by kchibisov — CHANGES_REQUESTED** [review]
I wonder why we're checking for dpi here and not in winit? I think it could and **should** be easily done there.

**Comment by kchibisov** [comment]
See https://github.com/rust-windowing/winit/pull/1403

**Comment by JOT85** [comment]
@kchibisov we should probably remove the check that was there in the first place since winit does it now.

**Comment by kchibisov** [comment]
we should, but with winit update, since check isn't released in winit yet.

**Pull request closed without merging**
