### PR TITLE
manpage: explain better `selection.save_to_clipboard`

### PR DESCRIPTION
**Pull request by doronbehar**
To avoid future questions like https://github.com/alacritty/alacritty/issues/8334

### CODE REVIEW

**Comment by kchibisov** [comment]
I'm not sure about this one, since this option applies to all platforms, and `primary` is probably more clear on them. Maybe replace primary with `regular`.

**Comment by doronbehar** [comment]
Do other platforms have more then 1 clipboard selection? I'm pretty sure Windows doesn't have that concept, and I couldn't find any mention of such concept when web searching for OSX related clipboard selections.

**Comment by kchibisov** [comment]
No, but on them we save what you select to regular clipboard, like on linux.

**Comment by kchibisov** [comment]
that's also the reason it's called `save_to_clipboard` and not `sync_clipboards` in the first place.

**Comment by doronbehar** [comment]
So do I understand correctly that by default this configuration option is turned off, and hence by default users of Darwin and Windows cannot copy anything from their terminal without turning this to `true`? Why would someone won't want to be able to copy something to their clipboard?

On GNU/Linux, it kind of makes sense to have this option - for those who from some reason don't want to spoil their `CLIPBOARD` selection, but still it should be `true` by default IMO.

**Comment by chrisduerr** [comment]
> So do I understand correctly that by default this configuration option is turned off, and hence by default users of Darwin and Windows cannot copy anything from their terminal without turning this to true? Why would someone won't want to be able to copy something to their clipboard?

**Selections** aren't copied automatically, which is the standard behavior on those platforms.

> On GNU/Linux, it kind of makes sense to have this option - for those who from some reason don't want to spoil their CLIPBOARD selection, but still it should be true by default IMO.

On Linux this option makes no sense, because you already have it writing to clipboard you can access at any time. You can just make use of multiple clipboards rather than having to decide which one you want.

**Comment by nixpulvis** [comment]
I agree that the documentation could make the expected behavior more clear. But it's platform dependent, and therefore not trivial to do. You can also find a lot of info on how clipboards are expected to work on other online resources, so it's not like it's impossible to figure out how this works. But if it were me, I'd probably be in favor of elaborating here too.

**Comment by chrisduerr** [comment]
> But if it were me, I'd probably be in favor of elaborating here too.

If anything, I'd be less elaborate and remove the word `primary`.

**Comment by kchibisov** [comment]
yeah, that could also work.

**Comment by nixpulvis** [comment]
Upon staring at the configuration page for a moment, I've convinced myself the current state of the documentation actually makes perfect sense.

> So do I understand correctly that by default this configuration option is turned off, and hence by default users of Darwin and Windows cannot copy anything from their terminal without turning this to true?

Since it's under the `[selection]` key, clearly it only applies to selections.

As for removing the word primary. I could see that avoiding some confusion. Curious what @doronbehar thinks too.

**Comment by nixpulvis** [comment]
> that's also the reason it's called save_to_clipboard and not sync_clipboards in the first place.

See that doesn't make sense to me. Syncing the clipboards makes more sense to me since it makes it more clear that the selection will be updated as you make it, while the normal copy action still uses the selection, just not without the action.

**Comment by kchibisov** [comment]
For copy action you need to press a button for it to happen. On linux once you select it always goes to primary clipboard.

Option does so whatever you select get saved in clipboard, meaning that on macOS/Windows/Linux whatever is selected goes to ctrl+c/v clipboard.

Sync would mean that platform has 2 clipboard buffers and whatever goes to any of them, goes to other clipboard. This is not what this option does, since if you use regular selection it won't go to _selection_ clipboard.

To _sync_ something you need more that one entity, but you have only 1, so nothing is synced (unless it's linux, but it's not _sync_ there either).

**Comment by nixpulvis** [comment]
> Sync would mean that platform has 2 clipboard buffers and whatever goes to any of them, goes to other clipboard. This is not what this option does, since if you use regular selection it won't go to selection clipboard.

That would be one interpretation. The other is that you are syncing the selection itself with the primary clipboard, but I do (and did) understand that typically clipboard sync means that it's syncing the two clipboards, which is why I'm not actually proposing using sync_ to help this issue.

**Comment by doronbehar** [comment]
What was confusing for me, was the fact that this `selection.save_to_clipboard` had nothing to do with any key bindings. And from some reason I assumed that <kbd>ctrl+LeftMouseKey</kbd> would copy the selection to the clipboard, and I was simply frustrated how that was defaulting to the `PRIMARY` selection. Reading the word "primary" in the docs confused me further, as that seemed like the current behavior.

I have several suggestions:

Replace the too generic:

> This section documents the [[selection]](https://alacritty.org/config-alacritty.html#s53) table of the configuration file.

With:

> This section documents settings related to selection of text (with the mouse? I'm not sure..).

And replace (more importantly):

> When set to true, selected text will be copied to the primary clipboard.

With:

> When set to true, selected text will be copied to the system's clipboard. NOTE that by default on GNU/Linux, for almost any program, selected text is always copied to a clipboard "selection" called `PRIMARY`. This behavior cannot be changed by this or any other setting, but setting the above to `true`, makes sure that the selection will also be copied to the clipboard selection named `CLIPBOARD`, even without pressing <kbd>Ctrl-Shift</kbd>, which is the default key binding for copying the selection to the `CLIPBOARD` clipboard selection.

**Pull request closed without merging**
