### PR TITLE
Fixing hint post processing close brackets.

### LINKED ISSUE #5492: Hint post processing crash
Alacritty with the following config crashes when hovering over the `)` character.

```yaml
hints:
  enabled:
   - regex: "[^/ ]"
     action: Paste
     post_processing: true
     mouse:
       enabled: true
       mods: None
```

It only crashes with post processing enabled and I get no relevant output with `-vvv` or `--print-events`.

`alacritty 0.9.0 (fed349aa)` on Linux + Wayland (sway)

### PR DESCRIPTION
**Pull request by gsfreema**
Fixes #5492 

When the match is as single character, don't exclude any character from the range during hint post processing. Otherwise, the HintPostProcessor can end up in an infinite loop it is iterated over.

### CODE REVIEW

**Comment by gsfreema** [comment]
It does make sense that the function should function the same regardless of the match length, but that does mean that it will return an invalid RangeInclusive<Point> since the end of the range will be before the start of the range which is what the current functionality does and why it's resulting in an infinite loop when iterating over it.

**Comment by gsfreema** [comment]
No worries. I can investigate some of those options. I had thought about an exclusive range but so many other pieces expected an inclusive range that I felt that was best to work with. According to the inclusive range docs, an end that is before the start is considered an empty range which is why I thought it might be ok to return.

**Comment by chrisduerr** [comment]
>  I had thought about an exclusive range but so many other pieces expected an inclusive range that I felt that was best to work with.

Yeah with an exclusive range you'd likely be checking if it's empty or not and then convert it immediately anyway. So at that point you might as well just return an option.

**Comment by chrisduerr** [comment]
Could you please rebase this on top of the latest master? It doesn't rebase cleanly and is not reviewable in its current state.

**Comment by roland-rollo** [comment]
Why do you close this?

**Comment by gsfreema** [comment]
My limited git knowledge left me with 32 files changes every time I tried rebasing on upstream/master. I don't really have the time to figure out why that kept happening so it was far easier and faster for me to update the single file necessary for a fix in a different branch and create a new PR.

**Pull request closed without merging**
