### PR TITLE
Fix backspace deleting chars when IME is open

### LINKED ISSUE #1606: macOS: unexpected characters get deleted when using backspace in Pinyin input method
Which operating system does the issue occur on? macOS 10.13

When input Chinese characters, if I use backspace to remove some letters ( as part of the Pinyin structure), it will get the characters which are just before the cursor of alacritty deleted (not what I intend to do). 
I have tested it with the input method in the gifs and macOS's default Pinyin input methods, and with the fresh installed alacritty on other people's maxOS (also 10.13), all reproduced the case.

gifs for different behaviors of alacritty and iTerm2.
alacritty
iterm2

### PR DESCRIPTION
**Pull request by chrisduerr**
Fixes #1606.

### CODE REVIEW

**Comment by kchibisov** [comment]
I'm wondering why Alacritty receiving characters when you're typing in IME window, it's seems to me like winit bug tbh, however I'm not familiar with macOS IME and it's fine to remove binding for a platform if it doesn't make any sense.

**Comment by chrisduerr** [comment]
> I'm wondering why Alacritty receiving characters when you're typing in IME window, it's seems to me like winit bug tbh

If you read the last few comments of the issue, you'll notice that we don't. What we do receive is keyboard input events, but no `ReceivedCharacter` events.

The problem is just that we map the \x7F character to backspace in our keybindings by default, since Linux would otherwise send \x08. But I've tested this on macOS and it already sends \x7F anyways, so that binding is not required here.

**Comment by kchibisov** [comment]
I mean they shouldn't be our window event, if you type backspace in a different window on X11, you'll see `Backspace`, but you wont execute anything. So in theory every binding to IME could trigger binding in alacritty, right? IIRC this is not true for e.g. X11 IME.

**Comment by chrisduerr** [comment]
> I mean they shouldn't be our window event, if you type backspace in a different window on X11, you'll see Backspace, but you wont execute anything.

You won't receive a WindowEvent though, but a DeviceEvent. That concept does not exist in this fashion on macOS (or Wayland actually).

**Comment by kchibisov** [comment]
Oh, I've got why iterm works, it's because it's entering chars in terminal while typing in IME, so backspace on IME is a backspace in terminal and it works fine. However we don't do that and we're just missing chars... So we should likely do what iterm is doing and just enter chars into terminal.

**Comment by chrisduerr** [comment]
We're not receiving any characters though. Winit only forwards key bindings, not characters.

So this just fixes the problem, no need to over-complicate things?

**Comment by kchibisov** [comment]
I know, I just found out an explanation why iterm works fine here, since I do remember that it has binding for backspace.

**Pull request merged**
