### PR TITLE
Update alacritty.5.scd

### PR DESCRIPTION
**Pull request by brunopeter**
fix markdown formatting

### CODE REVIEW

**Comment by kchibisov** [comment]
This is not markdown.

**Comment by brunopeter** [comment]
It is not being rendered properly in Github as currently formatted.

image

**Comment by kchibisov** [comment]
You're breaking the `.scd` file format, it won't compile with your changes. If github can't render file it's github problem not ours.

**Comment by nixpulvis** [comment]
This is unfortunately one drawback to the new documentation approach, however as I understand it once https://github.com/alacritty/website/pull/15 is merged and everything is released, then you'll be able to view the documentation online (in addition to locally through `man`) on alacritty.org.

**Comment by brunopeter** [comment]
Thank you very much for the additional background and explanation.

**Pull request closed without merging**
