### PR TITLE
[RFC] Experimental retry-loop to ameliorate clipboard error on Windows

### PR DESCRIPTION
**Pull request by cwedgwood**
Sometimes setting the clipboard on Windows fails, this is an experiment to address this.

### CODE REVIEW

**Comment by kchibisov** [comment]
Have you checked whether this is present with 5.0 version of the windows clipboard? In general, I think consumer of the API should do thing like that and what we should do is it indicate that the clipboard is busy?

**Review by chrisduerr — CHANGES_REQUESTED** [review]
Definitely not something appropriate for including into Alacritty. This is just a dirty hack and there's no technical necessity for this as far as I'm aware.

**Comment by cwedgwood** [comment]
> Have you checked whether this is present with 5.0 version of the windows clipboard? In general, I think consumer of the API should do thing like that and what we should do is it indicate that the clipboard is busy?

I have not, I couldn't get copypasta to accommodate this.

**Comment by cwedgwood** [comment]
@kchibisov @chrisduerr 

As a point of reference after 4 weeks of using this change I hit a single incident where it failed (after 3 attempts), so implementation details aside, whilst the concept helps it is insufficient.

Searching for similar errors I see other reports of transient clipboard access problems.

For now, I am going to rebuild using the main branch in the hope that some of the dependencies there have inadvertently addressed this.



Thanks!

**Pull request closed without merging**
