### PR TITLE
Add note about signing and notarization to README

### LINKED ISSUE #1896: macOS complains about an "unidentified developer"
Is there a way to mark this app as from an identified developer with macOS so I don't get the scary warning every time I launch this app after a restart of my computer?

### LINKED ISSUE #3448: macOS GateKeeper
It doesn't seem like the precompiled binary is signed with Apple. Is there a plan to have it added to your build process?

For context, this was all it took to have it signed and notarized:
```
make app
cd target/release/osx
codesign --options=runtime --force --verify --verbose --sign "[Use an Developer ID identity]" Alacritty.app
ditto -c -k --keepParent Alacritty.app Alacritty.app.zip
xcrun altool --notarize-app --primary-bundle-id "Alacritty.app.zip" --password "@keychain:[item stored in Keychain with your app-specific password]" --username "[typically your Apple ID]" --file Alacritty.app.zip
# wait about 5 minutes
xcrun stapler staple "Alacritty.app"
```

Reference: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

### LINKED ISSUE #4529: FR: Code Sign macOS app
For integrating into automatic download & distributions are  mechanisms (like https://github.com/autopkg/autopkg), it's helpful to be able to verify the app's code signature to ensure it hasn't been tampered with.  An Apple Dev code signature isn't necessary for our purposes, just looking for something that can checked against.

### System

OS: macOS
Version: 0.6.0
Linux/BSD: N/A
Windows: N/A

### Logs

N/A

### LINKED ISSUE #4673: Notarize macOS Binaries
Look, I'm no Apple apologist. I have publicly and vocally opposed Apple's rigid stance towards control of their platform time and again. And I always encourage people to put their time, money, and effort behind more open systems if the limitations they face are imposing. However, while I mostly avoid Apple (and Google, for that matter) in my personal life, there are professional scenarios here and there that require me to develop on and operate within the Apple ecosystem.  

If this project is ideologically opposed to Apple's ecosystem and the maintainers have "no interest" in supporting it: https://github.com/alacritty/alacritty/issues/1896#issuecomment-524436732, https://github.com/alacritty/alacritty/issues/1896#issuecomment-690677828, and https://github.com/alacritty/alacritty/issues/3448#issuecomment-598333977, then I don't think it's fair to list macOS as a supported platform.

Am I disappointed that the maintainers are not interested in supporting macOS? A little. It feels like others are being denied the opportunity to use a nice terminal emulator for largely personal reasons. But I'm mostly just interested accurately capturing reality. The reality is that when you attempt to run Alacritty on macOS, the system prompts you to move the software to the trash because its integrity cannot be verified by the platform. The release provided by this project _does not function_ within Apple's ecosystem.

There is a channel available for projects to receive a free developer program membership. It does not take more than a day total to sit down, apply for a tax-id, and then fill out the fee waiver application. The path exists to support macOS without paying Apple a cent. But the maintainers here have indicated they are not interested in taking it. It doesn't feel so much like macOS users who "made the mistake to purchase a macOS device" are facing a limitation of Apple's platform, but rather are caught amidst an ideological dispute between the maintainers of this project and Apple Inc.

Like it or not, supporting macOS entails signing or notarizing release binaries.

I came here to install Alacritty on macOS so I can have a consistent terminal emulator across the various platforms because the README says you support macOS. I would really like to avoid the conclusion, "use a different terminal emulator on macOS because Alacritty's maintainers don't like Apple and consider usage of hardware that runs macOS a mistake".

I'm willing to lend my time to help get this resolved if the effort required to setup a non-profit and apply for a tax-id and submit the fee waiver application is truly the only barrier.

### LINKED ISSUE #4731: MSI file is unsigned
### System
OS: Windows

Currently, it looks like the `.msi` installer isn't signed and thus, the browser is really reluctant to download it. Note the **Publisher: Unknown**
image

Windows also throws a warning before installing.
image

I don't know if this is a known issue (I did search for previous issues) and cannot be resolved due to some reasons. I am unaware of the signing and building process.

I ~went through your GitHub action yml file~ did some research and found out that  you use WiX. So I'm just pasting this here if it's of any help. https://stackoverflow.com/questions/17589754/wix-installer-msi-publisher-unknown

Thank you for the project!

### PR DESCRIPTION
**Pull request by nixpulvis**
Just figured I'd put this in the README to possible help our users understand our stance on the issue. Feel free to close if you'd rather not add anything.

fixes #1896
fixes #3448
fixes #4529
fixes #4673
fixes #4731

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
Hm I question the utility of this comment. People will probably find out that the application is signed themselves and building it from source doesn't really provide much benefit over having the binary built officially.

**Comment by nixpulvis** [comment]
I see that you have signed the release tags in git, which is probably the best thing an open source project can do. This ensures that the developers approve of the state of the code at the point of release to some degree. For people like me who build from source myself, this is all I really could want.

However, I don't think that matches the expectations of some users on macOS and Windows. When they ask for a signed (or notarized) build, they are asking for the actual binary (or perhaps installer) to be signed. And in fact, as we've discussed ad nauseam, they expect this signature to be coordinated by an authority which costs money to setup.

The goal of this addition to the README was to add a note next to the sentence about macOS and Windows builds to help explain that we do not attempt to perform this kind of signing.

I had considered linking to `.github/workflows/release.yml` to show how the build is generated, but I assumed that was overly verbose. Between the verified tag, and the released by "github-actions" messaging in https://github.com/alacritty/alacritty/releases (shown below) I feel like people should trust the build process. Though it's true, there's no automated (or manual) third party like Apple claiming to check out builds for malware.

20210203_12h54m53s_grim

**Comment by chrisduerr** [comment]
> I see that you have signed the release tags in git, which is probably the best thing an open source project can do.

Yes, that is so that distributions can verify the published code against my pgp key to validate its authenticity automatically when shipping software.

> The goal of this addition to the README was to add a note next to the sentence about macOS and Windows builds to help explain that we do not attempt to perform this kind of signing.

Does anyone *think* we are attempting this? I've yet to see anyone claim our signing process is broken.

**Comment by eruizc-dev** [comment]
You can easily workaround this error message (I've only tested this in Big Sur):

 ### For alacritty (or any app) only:
  1. Open it, you will see a message talking about unidentified developers and bla bla bla, dismiss it (don't trash the app...).
  2. Go into System Preferences -> Security and Privacy.
  3. At the bottom you should see Allow apps downloaded from, with alacritty listed below it. Click in Open Anyways.
  4. Profit.

### For all apps:
 1. Open terminal and run `sudo spctl --master-disable`.
 2. Done.
 3. If you go into Security and Privacy there should be a new option to allow apps downloaded from Anywhere.

Maybe add this info or pin this comment in the readme?

**Comment by nixpulvis** [comment]
@eruizc-dev part of the point is to make it clear we aren't interested in helping people navigate this aspect of their OS. If you're on  macOS frankly, you should already know how to do this, or be able to look it up.

This is distinct from our INSTALL.md instructions which are by necessity somewhat dependent on the OS and our application requirements.

The purpose of this PR was mainly to have a prominent place to point to for our position on notarization and paid signing.

-----

Also, I'm not sure I'd actually ever advertise disabling SIP entirely on an official recommended setup. Though I'm torn on the subject. Doing so has far greater implications to the OS than just enabling 3rd all party applications.

**Comment by chrisduerr** [comment]
Closing since I see no utility in this statement. The fact that our binaries are unsigned should be obvious and this does not help anyone who is running into this issue and uncertain how to proceed (not that I think Alacritty docs are the right place to do so).

**Pull request closed without merging**
