### PR TITLE
[docs] use curl instead of local files if possible

### PR DESCRIPTION
**Pull request by nyurik**
Some commands could be done using the in-memory temporary files instead of requiring users to clone the repo.  This way alacritty can be installed with `cargo install`, and the terminfo can be updated without any `git clone.  Although it might be worth while to set up a separate installation section for these tricks?

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
No, users should be cloning the repository.

**Comment by nyurik** [comment]
@chrisduerr but you already offer a non-cloning variant with `cargo install alacritty` -- why not help those users and document how to set up other things?

**Comment by chrisduerr** [comment]
I'd rather remove `cargo install` as an installation method. Which quite honestly nobody should be using anyway.

**Comment by nyurik** [comment]
Why? This is a fairly standard way for many rust utilities like lsd, and very convenient.  Cloning on the other hand involves extra steps that later have to be cleaned up. In sure there are many ppl who began using various programs just because they were so easy to install. Why purposefully make it more difficult to gain new users??

**Comment by kchibisov** [comment]
Alacritty is available in lots of distributions and using your distro package manager is always a preferred way. With cargo install you don't get extra files, terminfo(it's in ncurses now, but not on macOs for example), man pages, icons, desktop entries, and other documentation, like configuration file. So cloning is still required for all of that.

Using `cargo install` isn't that much useful here, unfortunately. Folks who want to install from crates io will always find it.

**Pull request closed without merging**
