### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by nixpulvis**
Well, I'm testing out... wait which OS am I on right now...

Anyway, this seems more canonical now, no?

### CODE REVIEW

**Comment by chrisduerr** [comment]
Is there *any* reason to actually change this? Doesn't `apt` internally still call `apt-get` anyway?

If this works just fine and there's no sign that it will ever break, I don't see why would change it?

**Comment by nixpulvis** [comment]
I got an error, apparently the system I was on didn't have `apt-get` but did have `apt`. Hard to say which is more popular, but I do think `apt` is pretty ubiquitous.

Let me double check the state of Ubuntu and Debian LTS stuff and report back.

**Review by kchibisov — APPROVED** [review]
Legacy systems have just `apt-get`(very old ones). More modern had both, and I think the transition is towards  `apt` anyway. At least on `Debian 11` I have `apt`.

**Comment by chrisduerr** [comment]
> I got an error, apparently the system I was on didn't have apt-get but did have apt

Which system is this?

**Comment by nixpulvis** [comment]
Pretty sure it was just the latest Ubuntu release. Haven't verified that.

**Pull request merged**
