### PR TITLE
Publish to Windows Package Managar (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @alacritty.

### CODE REVIEW

**Comment by kchibisov** [comment]
I don't understand why do we need this in the first place. The ones who should be responsible for package manifest for winget should be the ones who is responsible for winget, not us.

From what I can see alacritty is present on winget https://github.com/microsoft/winget-pkgs/blob/6ace2b585a12fddfcefedd74f8a0f226ec1cfe56/manifests/a/Alacritty/Alacritty/0.10.1/Alacritty.Alacritty.locale.en-US.yaml, so I don't think that we need any action here?

**Review by chrisduerr — CHANGES_REQUESTED** [review]
> It is present, but the manifest has to be updated with every new release of Alacritty.

Which is the job of the package maintainer, who shouldn't also be the developer.

**Comment by vedantmgoyal2009** [comment]
Well, here, the package maintainer is github actions :)

**Comment by kchibisov** [comment]
@vedantmgoyal2009 personally I dislike the idea of github workflow, since I think it's not audited? If folks do care about release to winget, they could send patches there, that would at least indicate that they audited the update and that it works...

That's how it works with all linux distros, homebrew, etc. Not sure how those are different from winget.

**Pull request closed without merging**
