### PR TITLE
man(5): align example [terminal] with doc

### PR DESCRIPTION
**Pull request by jchriskaiser**
Don't know if this is the proper way to suggest a really small fix that doesn't even touch upon any functionality, but since I noticed that today, I figured I'd just try.

### CODE REVIEW

**Review by kchibisov — APPROVED** [review]

**Review by chrisduerr — CHANGES_REQUESTED** [review]
This should not be using an inline table.

**Comment by chrisduerr** [comment]
> Don't know if this is the proper way to suggest a really small fix that doesn't even touch upon any functionality, but since I noticed that today, I figured I'd just try.


Could you explain how this fixes anything? From what I can tell it's just wrong.

**Comment by kchibisov** [comment]
@chrisduerr you need `[terminal.shell]` or the inline table, so either way is fine by me.

**Comment by chrisduerr** [comment]
> @chrisduerr you need [terminal.shell] or the inline table, so either way is fine by me.

This just documents the shell option though, not the terminal section. It matches how other things are documented in our example. Otherwise it would be at the end of the terminal section, which it is not.

**Comment by kchibisov** [comment]
I guess the point is that you can not really copy paste it anymore like any other stuff, since every other example uses the `top-level`.

Guess it should be just moved for terminal section example then.

**Comment by chrisduerr** [comment]
> I guess the point is that you can not really copy paste it anymore like any other stuff, since every other example uses the top-level.

I checked and this is not true for every example.

It's also not true that you can't copy-paste because of this. You just need to have an existing terminal section.

**Comment by chrisduerr** [comment]
Just as a follow-up, there's two possible solutions I'd consider here. Either changing the header to `[terminal.shell]`, so the header can stand on its own. Or using just the inline syntax `shell = { … }` without a header.

**Comment by jchriskaiser** [comment]
Thank you for considering this, and for your comments! I think you understood my intention already, so I'll just add a bit of context.

What I did: c&p the example into an empty `alacritty.toml`, and only adapt `program` and `args`.

What happened: I received a warning
> [WARN ] [alacritty_config_derive] Config warning: shell has been deprecated; use terminal.shell instead
> Use `alacritty migrate` to automatically resolve it

What I concluded: update of example might have been overlooked.

Besides: The following would not have worked either - even if I had not forgotten the `[terminal]` header:
```toml
[terminal]
[shell]
program = "/bin/zsh"
args = ["-l"]
```

**Comment by jchriskaiser** [comment]
> Just as a follow-up, there's two possible solutions I'd consider here. Either changing the header to `[terminal.shell]`, so the header can stand on its own. Or using just the inline syntax `shell = { … }` without a header.

I would favor the latter, as the `[terminal]` header is mentioned above, and this is also the syntax of the pattern in the doc.

**Review by chrisduerr — APPROVED** [review]

**Pull request merged**
