### PR TITLE
Alacritty Terminal version 0.21.0

### PR DESCRIPTION
**Pull request by chrisduerr**

### CODE REVIEW

**Comment by kchibisov** [comment]
Do we want to remove the `-dev` stuff from the `alacritty_terminal`?

**Comment by chrisduerr** [comment]
> Do we want to remove the -dev stuff from the alacritty_terminal?

Yes, since this is not a development version? It's a release.

**Comment by kchibisov** [comment]
@chrisduerr but we usually do that on separate branches and if you want to do something like that on master, you should probably update the `CONTRIBUTING.md` wrt how `alacritty_terminal` is released.

**Comment by chrisduerr** [comment]
> @chrisduerr but we usually do that on separate branches and if you want to do something like that on master, you should probably update the CONTRIBUTING.md wrt how alacritty_terminal is released.

Oh yeah good point, I had no intention of merging this into master. I wanted this to be on the same branch I have on my fork.

**Review by kchibisov — APPROVED** [review]

**Pull request merged**
