### PR TITLE
Fix for DEC Special Character Set (Line drawing)

### PR DESCRIPTION
**Pull request by kugland**
Fix for #6095.

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
Change looks good, could you fix the tests too? I think the easiest solution is probably to just edit the test files manually.

Also for reference: https://vt100.net/docs/vt220-rm/chapter2.html#T2-4

**Comment by kugland** [comment]
> Change looks good, could you fix the tests too? I think the easiest solution is probably to just edit the test files manually.
> 
> Also for reference: https://vt100.net/docs/vt220-rm/chapter2.html#T2-4

I just fixed the tests.

**Comment by j4james** [comment]
While you're in this area, note that this character set is also missing the mapping of `_` to blank. You can see the correct behavior in the XTerm screenshot posted in the original issue (#6095). It's also documented in the VT220 manual linked above.

**Comment by kugland** [comment]
> While you're in this area, note that this character set is also missing the mapping of `_` to blank. You can see the correct behavior in the XTerm screenshot posted in the original issue (#6095). It's also documented in the VT220 manual linked above.

Oh, I didn’t catch this! Now it’s fixed.

**Comment by kugland** [comment]
> While you're in this area, note that this character set is also missing the mapping of `_` to blank. You can see the correct behavior in the XTerm screenshot posted in the original issue (#6095). It's also documented in the VT220 manual linked above.

Same problem as before: this change made the tests fail. I fixed the tests now.

**Comment by kugland** [comment]
With this last commit, the result in Alacritty is the same as in XTerm:

image

**Review by chrisduerr — APPROVED** [review]
Thanks for the PR.

I've taken the liberty to add a changelog entry myself and everything should be good to go now.

**Comment by kugland** [comment]
> I've taken the liberty to add a changelog entry myself and everything should be good to go now.

@chrisduerr , in the line above the one you added, ‘built-in’ is written ‘buili-in.’

**Pull request merged**
