### PR TITLE
Implement basic smoothing of the cursor movement

### PR DESCRIPTION
**Pull request by GregTheMadMonk**
This is made by simply caching the previous cursor position and interpolating between it and the current position from frame to frame. This means rendering all of the frames, and an increased GPU load (which is comparable to watching a YouTube video), but that's just an optional feature that's off by default. Maybe the possible performance hit should be specified in the config template comments.
Also, turning the feature on switches block cursor to underline, because block cursor is rendered via replacing cell's fore-/background colors and you couldn't really interpolate there, unless there's a bigger change to the code.

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
Not even remotely interested in this feature.

**Comment by GregTheMadMonk** [comment]
Rude 😐

**Comment by chrisduerr** [comment]
If you didn't see that coming, that's 100% on you.

It should be obvious to anyone that Alacritty isn't the right project for adding pointless UI options that reduces performance. Doing so after issues specifically requesting this feature have been shot down is quite frankly just a rude waste of my time.

**Comment by GregTheMadMonk** [comment]
You wasted more time insisting on being an asshole after closing the issue than it would take any person to read this entire pull request.

> Then do it yourself lol.

I did. What's your problem now?

**Comment by merowingen** [comment]
This is a great feature that was very well received when it was released in kitty. I know a lot of people who switched to kitty only because of it. But kitty is *nix-only so I've wonder if there is any chances that alacritty one day might have something similar.

**Comment by TheAjaykrishnanR** [comment]
> This is a great feature that was very well received when it was released in kitty. I know a lot of people who switched to kitty only because of it. But kitty is *nix-only so I've wonder if there is any chances that alacritty one day might have something similar.

alacritty wont but [wezterm](https://github.com/wezterm/wezterm/discussions/1136) has a discussion on this and would most likely have an implementation in the future. Also I never understood people already on linux switching to kitty from alacritty, precisely as to why they chose alacritty to begin with.

**Pull request closed without merging**
