### PR TITLE
Make pre-0.13.0 configuration a note in README

### PR DESCRIPTION
**Pull request by kchibisov**
Rendered

image

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
What does this contribute? I don't see how this makes anything better and I'm not sure what this proprietary markdown looks like on crates.io for example.

**Comment by kchibisov** [comment]
Hm, that's fair, it probably look broken on crates.io.

Maybe we should just move it below, since 0.13.0 is out?

**Comment by chrisduerr** [comment]
> Maybe we should just move it below, since 0.13.0 is out?

Sure, I'm also fine with just removing it.

**Comment by kchibisov** [comment]
I've just removed it.

**Review by chrisduerr — APPROVED** [review]

**Pull request merged**
