### PR TITLE
Remove alacritty.spec

### PR DESCRIPTION
**Pull request by chrisduerr**
Since Alacritty is now officially packaged by Fedora, it is no longer
necessary to provide this in the official repository.

### CODE REVIEW

**Comment by pschyska** [comment]
@chrisduerr I think you can remove `.copr/Makefile` as well. Cheers

**Comment by chrisduerr** [comment]
@pschyska Thanks, I didn't see that!

**Comment by kchibisov** [comment]
Should we add a note in packaging section that we've removed copr stuff?

**Comment by pschyska** [comment]
> Should we add a note in packaging section that we've removed copr stuff?

It wouldn't hurt, I guess? I've spoken to a number of copr users that didn't know it's now upstream.

**Comment by chrisduerr** [comment]
> Should we add a note in packaging section that we've removed copr stuff?

And who would that be for? The maintainer of the copr already knows about it. The packaging section is *for packagers*, not to inform users about packaging.

**Comment by kchibisov** [comment]
I was thinking about the ones who might used our copr stuff for their own copr jobs or something like that, besides @pschyska . But I think it's fine without mentioning it.

**Pull request merged**
