### PR TITLE
style: simplify string formatting

### PR DESCRIPTION
**Pull request by hamirmahal**

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
The changes here shouldn't result in any user-facing changes. They're just to improve code readability and maintainability.

**Comment by chrisduerr** [comment]
@kchibisov Do you have any feelings about this? I personally don't really want to enforce always having things inlined, because it's not really possible anyway. But it has been done for a couple of format strings in Alacritty already and consistency is nice. If we just allow both, I see no reason to merge this PR.

**Comment by kchibisov** [comment]
Honestly, I don't really care that much. In general I do like the inline syntax more, but as said, it's not possible to use with everything...

**Review by chrisduerr — APPROVED** [review]
Going to merge this for now as the generally preferred way if possible. But I'd rather not see more PRs like this in the future.

**Pull request merged**
