### PR TITLE
Don't obscure normal cursor with hyperlink preview

### LINKED ISSUE #6325: On-hover hyperlink target text obscures prompt
When I hover over a hyperlink, alacritty displays the link target at the bottom of the screen. This obscures the prompt and in particular I have the following problem:

- Background: I switch between other MacOS apps and full-screen Alacritty using a single key (configured in hammerspoon)
- Sometimes, when I switch back to Alacritty, I expect to be able to start typing immediately at a prompt, but the hyperlink target  on-hover text is obscuring the prompt.

To be clear, this is the hyperlink target on-hover text I'm referring to:

image
☝️ my prompt is underneath that black bar. The lines above are from `git log`.

I couldn't see options to configure this behavior.

[Thanks very much for Alacritty; I've recently switched. Apart from anything else, the plain text configuration file that I can keep under version control is a huge advantage over the graphical configuration tool in the terminal emulator I was previously using, and setting keybindings to send tmux commands was really easy.]

### System

OS: MacOS
Version: `alacritty 0.11.0-rc1 (7cd180da)`

### Logs

<details>

<summary>-vv and --print-events output</summary>

```
[0.000015630s] [INFO ] [alacritty] Welcome to Alacritty
[0.000299252s] [INFO ] [alacritty] Version 0.11.0-rc1 (7cd180da)
[0.001184529s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/ddavison/.config/alacritty/alacritty.yml"
[0.001992130s] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8
[0.035365562s] [DEBUG] [alacritty] Loading "Monaco" font
[0.105109091s] [DEBUG] [alacritty] Estimated scaling factor: 2
[0.105188523s] [DEBUG] [alacritty] Estimated window size: None
[0.105206552s] [DEBUG] [alacritty] Estimated cell size: 16 x 37
[0.184395393s] [INFO ] [alacritty] Running on AMD Radeon Pro 5500M OpenGL Engine
[0.184437551s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.192196058s] [INFO ] [alacritty] Display scale factor: 2
[0.192259409s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.197572851s] [INFO ] [alacritty] Cell size: 16 x 37
[0.197604600s] [INFO ] [alacritty] Padding: 14 x 14
[0.197620370s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.241177560s] [INFO ] [alacritty] PTY dimensions: 31 x 98
[0.244045939s] [INFO ] [alacritty] Initialisation complete
[0.254800402s] [DEBUG] [alacritty_terminal] New num_cols is 222 and num_lines is 59
[0.256936816s] [INFO ] [alacritty] Padding: 14 x 14
[0.256978463s] [INFO ] [alacritty] Width: 3584, Height: 2240
[0.386563940s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1''3''3'],['A'],] at line 963
[0.386622794s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1''3''3'],['B'],] at line 963
[5.159071845s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1''3''3'],['A'],] at line 963
[5.159114118s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1''3''3'],['B'],] at line 963
[5.159442812s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1''3''3'],['A'],] at line 963
[5.159465404s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1''3''3'],['B'],] at line 963
[6.462313812s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1''3''3'],['A'],] at line 963
[6.462360600s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1''3''3'],['B'],] at line 963
[7.071402716s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1''3''3'],['A'],] at line 963
[7.071465513s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1''3''3'],['B'],] at line 963
[7.660595511s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1''3''3'],['D'],['0'],] at line 963
[7.673084681s] [INFO ] [alacritty] Goodbye
```

```
Created log file at "/var/folders/cx/zsz9j5qd11n8wd8_51y1dvdh0000gp/T/Alacritty-40650.log"
[0.000002980s] [INFO ] [alacritty] Welcome to Alacritty
[0.000230072s] [INFO ] [alacritty] Version 0.11.0-rc1 (7cd180da)
[0.001091331s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/ddavison/.config/alacritty/alacritty.yml"
[0.024340766s] [INFO ] [alacritty] glutin event: NewEvents(Init)
[0.024389821s] [INFO ] [alacritty] glutin event: Resumed
[0.101346147s] [INFO ] [alacritty] Running on AMD Radeon Pro 5500M OpenGL Engine
[0.101390030s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.106479868s] [INFO ] [alacritty] Display scale factor: 2
[0.111198411s] [INFO ] [alacritty] Cell size: 16 x 37
[0.111231095s] [INFO ] [alacritty] Padding: 14 x 14
[0.111247225s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.137785676s] [INFO ] [alacritty] PTY dimensions: 31 x 98
[0.140326572s] [INFO ] [alacritty] Initialisation complete
[0.144772038s] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(WindowId(140294008903376)))
[0.152462616s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140294008903376)), event: Resized(PhysicalSize { width: 1600, height: 1200 }) }
[0.152517389s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140294008903376)), event: Moved(PhysicalPosition { x: 992, y: 340 }) }
[0.152542285s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140294008903376)), event: Resized(PhysicalSize { width: 3584, height: 2240 }) }
[0.152560132s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140294008903376)), event: Moved(PhysicalPosition { x: 0, y: 0 }) }
[0.152579066s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.152595364s] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(WindowId(140294008903376)))
[0.152611522s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.154873105s] [INFO ] [alacritty] Padding: 14 x 14
[0.154914540s] [INFO ] [alacritty] Width: 3584, Height: 2240
[0.181937170s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025472529076 }, requested_resume: None })
[0.196047823s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140294008903376)), event: Focused(true) }
[0.196099734s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.196117421s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.197308656s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025487912121 }, requested_resume: None })
[0.207540726s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.207605823s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.207633755s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025498237740 }, requested_resume: None })
[0.207663858s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.207680982s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.207699973s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025498306169 }, requested_resume: None })
[0.207735474s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.207753623s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.207984515s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025498378185 }, requested_resume: None })
[0.208054438s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.208079416s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.208102070s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025498706564 }, requested_resume: None })
[0.208530107s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140294008903376)), event: CursorEntered { device_id: DeviceId(DeviceId) } }
[0.208606861s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.208624896s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.208645014s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025499250451 }, requested_resume: None })
[0.208739885s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.208755988s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.210831455s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025499377936 }, requested_resume: None })
[0.210884341s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.210903290s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.210919375s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025501525165 }, requested_resume: None })
[0.210939565s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.210953659s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.212214570s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025501576967 }, requested_resume: None })
[0.212491080s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.212538858s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.214002490s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025503180032 }, requested_resume: None })
[0.214097594s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.214123140s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.214142037s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025504747073 }, requested_resume: None })
[0.214167554s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.214220495s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.217145985s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025504843695 }, requested_resume: None })
[0.217208817s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.217244768s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.217283615s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025507889264 }, requested_resume: None })
[0.217322261s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.217335575s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.220322130s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025507956988 }, requested_resume: None })
[0.220434210s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.220453343s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.220493884s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025511099448 }, requested_resume: None })
[0.220514844s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.220528963s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.223625759s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025511150572 }, requested_resume: None })
[0.223679730s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.223697372s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.223715900s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025514321101 }, requested_resume: None })
[0.223738334s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.223752285s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.225596449s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025514373906 }, requested_resume: None })
[0.225678187s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140294008903376)), event: Occluded(false) }
[0.225707888s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.225721689s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.225740233s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025516345123 }, requested_resume: None })
[0.225777600s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.225793298s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.226724636s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025516415171 }, requested_resume: None })
[0.226794776s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.226832757s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.226867627s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025517472954 }, requested_resume: None })
[0.226889819s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.226904465s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.229808675s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025517526725 }, requested_resume: None })
[0.229865995s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.229904655s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.229922551s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025520528304 }, requested_resume: None })
[0.229943583s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.229956774s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.233872935s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025520578294 }, requested_resume: None })
[0.233928130s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.233946877s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.233965853s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025524571135 }, requested_resume: None })
[0.233988476s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.234002765s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.236943514s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025524625046 }, requested_resume: None })
[0.236998305s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.237017380s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.237035569s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025527640898 }, requested_resume: None })
[0.237057569s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.237070990s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.240289573s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025527692891 }, requested_resume: None })
[0.240337811s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.240355989s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.240374206s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025530979638 }, requested_resume: None })
[0.240396918s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.240411283s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.244020072s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025531033508 }, requested_resume: None })
[0.244085106s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.244104473s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.244123082s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025534728362 }, requested_resume: None })
[0.244145916s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.244160257s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.266013449s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025534782206 }, requested_resume: None })
[0.266063710s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(140294008903376))), payload: Terminal(PtyWrite([1;1R)) })
[0.266091068s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(140294008903376))), payload: Terminal(Wakeup) })
[0.266106794s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.266119811s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.266686190s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025557290880 }, requested_resume: None })
[0.266718342s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(140294008903376))), payload: Terminal(Wakeup) })
[0.266736592s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.266749540s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.349307850s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025565675708 }, requested_resume: None })
[0.349702936s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.349724440s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.351329265s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025640347275 }, requested_resume: None })
[0.351529020s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.351575060s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[1.287099749s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142025642212650 }, requested_resume: None })
[1.287219682s] [INFO ] [alacritty] glutin event: MainEventsCleared
[1.287240023s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[1.396765773s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142026577877831 }, requested_resume: None })
[1.397359310s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140294008903376)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Pressed, virtual_keycode: Some(LControl), modifiers: CTRL }, is_synthetic: false } }
[1.397400149s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140294008903376)), event: ModifiersChanged(CTRL) }
[1.397416704s] [INFO ] [alacritty] glutin event: MainEventsCleared
[1.397429317s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[1.828262332s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142026688059713 }, requested_resume: None })
[1.834327851s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140294008903376)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 2, state: Pressed, virtual_keycode: Some(D), modifiers: CTRL }, is_synthetic: false } }
[1.834396572s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140294008903376)), event: ReceivedCharacter('\u{4}') }
[1.834410889s] [INFO ] [alacritty] glutin event: MainEventsCleared
[1.834427040s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[1.844645742s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142027125059052 }, requested_resume: None })
[1.844720252s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(140294008903376))), payload: Terminal(Wakeup) })
[1.844773382s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(140294008903376))), payload: Terminal(Wakeup) })
[1.844786653s] [INFO ] [alacritty] glutin event: MainEventsCleared
[1.844818937s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[1.851689062s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 142027136155647 }, requested_resume: None })
[1.851807683s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(140294008903376))), payload: Terminal(Exit) })
[1.852282767s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(140294008903376))), payload: Terminal(Wakeup) })
[1.852335687s] [INFO ] [alacritty] glutin event: MainEventsCleared
[1.852349956s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[1.852543024s] [INFO ] [alacritty] glutin event: NewEvents(Poll)
[1.852589447s] [INFO ] [alacritty] glutin event: LoopDestroyed
[1.852683287s] [INFO ] [alacritty] Goodbye
Deleted log file at "/var/folders/cx/zsz9j5qd11n8wd8_51y1dvdh0000gp/T/Alacritty-40650.log"
```

### PR DESCRIPTION
**Pull request by kchibisov**
Fixes #6325.

### CODE REVIEW

**Comment by dandavison** [comment]
(@chrisduerr I'm the person who reported #6325, thanks very much for Alacritty, I'm enjoying it a lot.)

Thanks for working on this @kchibisov! 

This works well as a solution for the scenario I described but I do have one question.


**Here we see your solution helping: the pager is still active, and I'm able to see that:**
<table>
    <tbody>
        <tr>
            <td>image
</td>
        </tr>
    </tbody>
  </table>

<br>
<br>
<br>

**And here again it helps, the pager is not active, and I'm able to see that and use the prompt**
<table>
    <tbody>
        <tr>
            <td>image
</td>
        </tr>
    </tbody>
  </table>

<br>
<br>
<br>


**My question is: will users find it odd for the on-hover text to be "floating" away from the bottom in this case, when their prompt is not at the bottom?**

<table>
    <tbody>
        <tr>
            <td>image
</td>
        </tr>
    </tbody>
  </table>

I'm probably about to ask a stupid question but does a terminal emulator have any way of knowing that the applications running inside it have not written beyond a certain point on the screen? I.e. can we reliably detect this case and place the hover text at the bottom?

**Comment by kchibisov** [comment]
>I'm probably about to ask a stupid question but does a terminal emulator have any way of knowing that the applications running inside it have not written beyond a certain point on the screen? I.e. can we reliably detect this case and place the hover text at the bottom?

In general we don't know that, but we always show at the bottom and move it to not obscure anything.

**Comment by kchibisov** [comment]
>My question is: will users find it odd for the on-hover text to be "floating" away from the bottom in this case, when their prompt is not at the bottom?

It won't float away from the bottom. On your screenshot I'd assume it's a padding?

**Comment by dandavison** [comment]
> It won't float away from the bottom. On your screenshot I'd assume it's a padding?

Oh, sorry! You're right, it's a padding and there's no difference between that on your branch versus the released version. So I don't have any questions! And I see that the pointer and the banner automatically avoid each other when they are together near the bottom:

<table>
    <tbody>
        <tr>
            <td>image
</td>
<td>image
</td>
        </tr>
    </tbody>
  </table>

So I think your work solves my problem -- thanks a lot.

**Review by chrisduerr — APPROVED** [review]

**Pull request merged**
