### PR TITLE
Add macOS ARM builds to CI

### PR DESCRIPTION
**Pull request by chrisduerr**

### CODE REVIEW

**Comment by christophwitzko** [comment]
The reason for the failing `macos-11.0` checks: https://github.com/actions/virtual-environments/issues/2486

**Comment by chrisduerr** [comment]
@christophwitzko Thanks a lot for letting me know, that is very helpful. I'd personally much prefer if `macos-latest` would be macos-11.0 anyways, so I have no trouble with waiting a bit. Until then people can still build from this branch just fine should they need the binary.

**Comment by christophwitzko** [comment]
@chrisduerr I agree 👍

**Review by pnegahdar — APPROVED** [review]

**Comment by osdiab** [comment]
hi, i'm looking forward to this! So I tried to build it myself, but ran into this issue:

```
  = note: ld: framework not found CoreServices
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Not sure if I'm being dense and didn't install something properly; I have XCode 12.4 installed and am on the latest beta release of Mac OSX, on an M1 Macbook Air. Is there something extra that needs to happen for builds to work?

After looking around a bit on the web, i was wondering if this issue is relevant: https://github.com/ronaldoussoren/pyobjc/issues/309

Anyway, thanks and hope for this to get in sometime :)

**Comment by osdiab** [comment]
Update, I happened to switch to a different laptop and for some reason it worked when I did exactly the same thing here. Maybe something was weird about my environment lol

**Comment by mrjones2014** [comment]
Hi, I'm following the instructions in the changes here trying to compile for M1 Mac, but when I launch the built application, `name -m` still outputs `x86_64` and ` sysctl -in sysctl.proc_translated` still outputs `1` meaning the app is still running through Rosetta 2 and not natively on ARM.

Is there anything I need to do to tell the universal app to run the ARM version?

**Comment by cormacrelf** [comment]
Are you sure those two commands are referring to the alacritty process and not e.g. your shell? 

You should be aware of the structure of processes' arm-ish-ness. Each can be running natively or under Rosetta, but also has a "arch preference for new child processes" which is either inherited or forced with the arch command. If any parent process of alacritty is run under Rosetta without forcing the preference back, then alacritty will run under Rosetta. If any process between alacritty and your shell is default Rosetta then so is your shell. Etc. Look at Activity Monitor, view all processes hierarchically, show the arch column, look at the tree involving the shell and alacritty.

```

Apple Terminal (arm64, default arm64)
--- starts shell (arm64 only, default arm64)
    --- starts sudo (universal => arm64, default arm64)
        --- attempts to load arm64 binaries into arm64 program

Apple Terminal (Rosetta, default Rosetta)
--- starts tmux server (arm64 only, default Rosetta)
    --- starts shell (arm64 only, default Rosetta)
        --- starts sudo (universal => Rosetta, default Rosetta)
            --- attempts to load x86_64 binaries into Rosetta program

```

**Comment by mrjones2014** [comment]
@cormacrelf actually, it was my mistake, sorry about that. I was in tmux and when I restarted the tmux server it started reporting correctly, since I had started it the first time from an x86 terminal  emulator.

**Comment by tami5** [comment]
Any updates on getting m1/arm version?

**Comment by chrisduerr** [comment]
> Any updates on getting m1/arm version?

ARM version for macOS will be made available as soon as GitHub has proper support for it. So asking for updates here is useless, since I can't do anything about that.

**Comment by tami5** [comment]
Thanks so much for your time and effort @chrisduerr. Is it though possible to build an arm version from source?

**Comment by chrisduerr** [comment]
Nothing should prevent you from building an ARM version from source.

**Comment by mhanberg** [comment]
If you are interested in potentially getting earlier access to the macOS 11 runner, it looks like they're accepting requests via a form. https://github.com/actions/virtual-environments/issues/2486#issuecomment-853514922

**Comment by shaunsingh** [comment]
In the meantime, here's an apple-silicon native binary I compiled myself 
[Alacritty.app.zip](https://github.com/alacritty/alacritty/files/6634802/Alacritty.app.zip)

**Comment by kenips** [comment]
> In the meantime, here's an apple-silicon native binary I compiled myself
> [Alacritty.app.zip](https://github.com/alacritty/alacritty/files/6634802/Alacritty.app.zip)

@shaunsingh kind enough to recompile for macOS 11.x please? Right now it's targeted for 12. <3

**Comment by khoi** [comment]
Here is the arm64 version I built on macOS 11 :) 
[Alacritty.app.zip](https://github.com/alacritty/alacritty/files/6645485/Alacritty.app.zip)

**Comment by aminroosta** [comment]
@khoi Tells me it's damaged.

**Comment by mhanberg** [comment]
Looks like macOS 11 virtual environments will be opening to the public sometime next week: https://github.com/actions/virtual-environments/issues/2486#issuecomment-885458538

**Comment by kurko** [comment]
For those who want to use this but aren't sure about the steps, here they are.

First, install `rustup`:

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh && \
  source $HOME/.cargo/env
```

Then run the following to build Alacritty (edit to your liking). It should take a couple minutes total.

```
git clone git@github.com:alacritty/alacritty.git && \
  cd alacritty && \
  git checkout arm_ci && \
  rustup update && \
  rustup target add aarch64-apple-darwin && \
  cargo check --target=aarch64-apple-darwin && \
  make dmg-universal && \
  cp -r target/release/osx/Alacritty.app /Applications/
```

There you go, Alacritty is now on your Applications folder.

**Comment by shaunsingh** [comment]
Since the arm_ci branch is a few months outdated now, I would recommend 
1. cloning alacritty at the `master` branch
2. copying over the /.github/workflows folder from the `arm_ci` branch to the `master` branch
3. copying over the makefile from the `arm_ci` branch to the `master` branch

```
rustup update && \
  rustup target add aarch64-apple-darwin && \
  cargo check --target=aarch64-apple-darwin && \
  make dmg-universal && \
  cp -r target/release/osx/Alacritty.app /Applications/
```

That way you can get a universal binary with all the latest fixes from `master`

**Comment by tommynguyen-vungle** [comment]
> Since the arm_ci branch is a few months outdated now, I would recommend
> 
> 1. cloning alacritty at the `master` branch
> 2. copying over the /.github/workflows folder from the `arm_ci` branch to the `master` branch
> 3. copying over the makefile from the `arm_ci` branch to the `master` branch
> 
> ```
> rustup update && \
>   rustup target add aarch64-apple-darwin && \
>   cargo check --target=aarch64-apple-darwin && \
>   make dmg-universal && \
>   cp -r target/release/osx/Alacritty.app /Applications/
> ```
> 
> That way you can get a universal binary with all the latest fixes from `master`

Thanks @shaunsingh 

My approach:

1. Clone Alacritty
2. `git checkout arm_ci`
3. `git rebase master`, and keep whatever new in `arm_ci` branch
4. Profit!
```
rustup update && \
  rustup target add aarch64-apple-darwin && \
  cargo check --target=aarch64-apple-darwin && \
  make dmg-universal && \
  cp -r target/release/osx/Alacritty.app /Applications/
```

**Comment by tuannvm** [comment]
> Since the arm_ci branch is a few months outdated now, I would recommend
> 
> 1. cloning alacritty at the `master` branch
> 2. copying over the /.github/workflows folder from the `arm_ci` branch to the `master` branch
> 3. copying over the makefile from the `arm_ci` branch to the `master` branch
> 
> ```
> rustup update && \
>   rustup target add aarch64-apple-darwin && \
>   cargo check --target=aarch64-apple-darwin && \
>   make dmg-universal && \
>   cp -r target/release/osx/Alacritty.app /Applications/
> ```
> 
> That way you can get a universal binary with all the latest fixes from `master`

Thanks @shaunsingh 

My approach:

1. Clone Alacritty
2. `git checkout arm_ci`
3. `git rebase master`, and keep whatever new in `arm_ci` branch
4. Profit!
```
rustup update && \
  rustup target add aarch64-apple-darwin && \
  cargo check --target=aarch64-apple-darwin && \
  make dmg-universal && \
  cp -r target/release/osx/Alacritty.app /Applications/
```

**Comment by shaunsingh** [comment]
Even better! I should learn github comments sometime soon

**Comment by mhanberg** [comment]
https://github.blog/changelog/2021-08-16-github-actions-macos-11-big-sur-is-generally-available-on-github-hosted-runners/

**Comment by chrisduerr** [comment]
@mhanberg Thanks for the heads-up. Was expecting the linked issue to get updated but this works too.

**Comment by deybhayden** [comment]
Building from source worked for me! Curious if anyone knows about getting the M1 builds here into Homebrew? I'm definitely a bit past my skis to know if it's possible to support the multiple architectures in the brew formula.

**Comment by chrisduerr** [comment]
Will likely be in homebrew once 0.10.0 is released. Which should be pretty soon-ish.

**Comment by jsekerez** [comment]
Hey, sorry but I'm having issues building the universal binary from source. I end up getting a whole bunch of errors as illustrated below when running `make app-universal` or `make dmg-universal`. I have no problem building the x86 version.

I've tried following the installation guide and following these comments' advice, including reinstalling tools like `rustup` and re-cloning the repo, but to no avail. Is there anywhere that I can find the M1 build somewhere else? I don't think it's in Homebrew. 
Screen Shot 2022-08-18 at 2 53 57 PM


Any advice?

**Comment by kchibisov** [comment]
The image from release page should work. In homebrew it's under cask.

If you want to build from source ensure that you have toolchain installed with the standard library, since it seems like it's missing. The target is `aarch64-apple-darwin` and you'd need `rustup target add aarch64-apple-darwin` and also have `rustup target add x86_64-apple-darwin`.

**Comment by jsekerez** [comment]
I downloaded it with Homebrew under cask. @kchibisov  Thank you so much!

**Pull request merged**
