### PR TITLE
Add config option for text reflow on resize

### LINKED ISSUE #4424: Add option to disable text reflow
This was requested in https://github.com/alacritty/alacritty/issues/4419.

It might make sense to some users to completely disable text reflow, however #4419 is the first time I've heard a user actually request the ability to change this in the configuration file. I'd be curious if there are other people interested in disabling this.

Fundamentally, the only real issue with it is the integration with shells, however some shells do already have patches available to work around these issues. So it might be questionable whether it makes sense to add a config option to work around an issue that can be completely fixed without losing any functionality.

### PR DESCRIPTION
**Pull request by chrisduerr**
Fixes #4424.

### CODE REVIEW

**Comment by chrisduerr** [comment]
I'm not sure how many people are actually interested in disabling this, so I'm curious about anyone interested in doing so. If not, the better solution is likely just to scrap this PR and the associated issue.

**Comment by nixpulvis** [comment]
I personally don't ever want to lose terminal content on accident, so I can't see myself disabling this feature. I might be more interested in a reflow delay configuration personally, but that's another topic.

**Comment by marcusatiliusregulus** [comment]
@chrisduerr in [4424](https://github.com/alacritty/alacritty/issues/4424#issuecomment-819143636)

i **would like this feature to disable reflow** because i am using fish-shell/fish-shell as my shell and cant get the commandline reflow working. This is a [link](https://matrix.to/#/!YLTeaulxSDauOOxBoR:matrix.org/$5wns7GZSoEs25BReycdz2TiGoU7mDvP1ZDtIGkF-apg?via=matrix.org&via=gitter.im&via=enactive.net) to a discussion about this on matrix. Sometimes the reflow works, sometimes it doesnt, i cant figure out a pattern. Enableing or disableing reflow handling in fish does not seem to do much even tho it first appeared so.

**Comment by chrisduerr** [comment]
@marcusatiliusregulus Have you tried this patch? Are you actually willing to throw away terminal content to achieve this?

**Review by mrkingfoxx — APPROVED** [review]

**Review by Rada8732 — APPROVED** [review]

**Comment by marcusatiliusregulus** [comment]
@chrisduerr ive now tried the patch but it sadly did not help with my investigation. thanks anyways!

**Comment by chrisduerr** [comment]
Closing since there has been no feedback justifying this addition.

**Pull request closed without merging**
