### PR TITLE
Prefer environment variables over passwd

### PR DESCRIPTION
**Pull request by TitanNano**
If the `passwd` lookup for any reason fails, the entire TTY creation fails as well. It is actually more desirable to check the matching environment variables for `USER`, `LONGNAME` and `HOME` first before trying to access the `passwd`. This is actually already being done for `SHELL`.

### CODE REVIEW

**Comment by chrisduerr** [comment]
> If the passwd lookup for any reason fails, the entire TTY creation fails as well.

"For any reason"? What reason would that be?

> It is actually more desirable to check the matching environment variables for USER, LONGNAME and HOME first before trying to access the passwd.

Source?

**Review by chrisduerr — CHANGES_REQUESTED** [review]
Generally I'd say the environment variables have a much higher chance of failing than the `passwd` lookup. Not being able to read `passwd` will break **numerous** applications that try to do the same thing.

I'd be fine with looking up the environment variables first and falling back to passwd if those are unset. But environment variables alone are insufficient.

**Comment by TitanNano** [comment]
> Generally I'd say the environment variables have a much higher chance of failing than the `passwd` lookup. Not being able to read `passwd` will break **numerous** applications that try to do the same thing.
> 
> I'd be fine with looking up the environment variables first and falling back to passwd if those are unset. But environment variables alone are insufficient.

The patch currently tries to fetch each of the environment variables and if a variable fails it falls back to the matching value in the Passwd struct.

**Comment by chrisduerr** [comment]
> The patch currently tries to fetch each of the environment variables and if a variable fails it falls back to the matching value in the Passwd struct.

Oh sorry, I didn't look at the patch close enough.

**Comment by chrisduerr** [comment]
Will try to get a review done today or tomorrow, just fyi.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

**Review by chrisduerr — APPROVED** [review]

**Pull request merged**
