### PR TITLE
Release some permissions to allow users to access and parse into stan…

### PR DESCRIPTION
**Pull request by jm-observer**
Release some permissions to allow users to access and parse into standard output #8172:

```
let row_cells: Vec<&Row<Cell>> =  term.grid_mut().raw_data().into_iter().rev().collect();
let mut lines = Vec::with_capacity(row_cells.len());
let mut line = String::new();
for row_cell in row_cells {
    let len = row_cell.line_length();
    if row_cell[Column(row_cell.len() - 1)]
        .flags.contains(Flags::WRAPLINE)
    {
        row_cell.into_iter().for_each(|x| line.push(x.c));
    } else {
        row_cell[Column(0)..Column(len.0)]
            .iter()
            .for_each(|x| line.push(x.c));
        let mut new_line = String::new();
        std::mem::swap(&mut line, &mut new_line);
        lines.push(new_line);
    }
}
```

### CODE REVIEW

**Comment by jm-observer** [comment]
Does this unsuccessful check not affect the merge?

**Comment by chrisduerr** [comment]
> Does this unsuccessful check not affect the merge?

Seems to be a temporary issue, I'll handle that no worries.

Accessing the underlying grid makes sense to me, but I thought we have indexing methods on the grid already? It seems like everything you want can be implemented with the current API.

Also your code example is not going to work in a reasonable time for big grids. You can essentially **never** create a complete duplicate representation of the entire scrollback, since cloning the grid alone would block your terminal mutex for **seconds**.

**Comment by jm-observer** [comment]
> but I thought we have indexing methods on the grid already? It seems like everything you want can be implemented with the current API.

[debug_assert!(requested.0 < self.visible_lines as i32);](https://github.com/jm-observer/alacritty/blob/7167ffe316fbb98e4e6021b9066ae551a445c4e7/alacritty_terminal/src/grid/storage.rs#L226)

Here, the range of data that users can access is limited.
```
    fn compute_index(&self, requested: Line) -> usize {
        debug_assert!(requested.0 < self.visible_lines as i32);

        let positive = -(requested - self.visible_lines).0 as usize - 1;

        debug_assert!(positive < self.len);
```

> Also your code example is not going to work in a reasonable time for big grids. You can essentially **never** create a complete duplicate representation of the entire scrollback, since cloning the grid alone would block your terminal mutex for **seconds**.

- My use case is that the program has already completed successfully, and I need to retrieve part of its output. 
- I have already verified that this implementation is feasible.
- Maybe we can add some risk warnings and let users make their own judgment.

**Comment by chrisduerr** [comment]
> Here, the range of data that users can access is limited.

I'm not sure what you're trying to say here. You're aware the lines in the scrollback history have a negative index?

**Comment by jm-observer** [comment]
Actually, I’m not sure either. However, I still hope to merge this PR because it saves me from having to calculate various regions and indices (I initially didn't realize that indices could be negative due to not fully understanding these relationships).

**Review by chrisduerr — CHANGES_REQUESTED** [review]
This method returns a Vec, when a slice should be sufficient. It also requires mutable access just to truncate, when truncation is unnecessary. As discussed, the same functionality can already be achieved without any changes and there's several grid methods that help with iterating over individual cells.

Additionally in your implementation using this API, you seem to push the responsibility of managing performance on the enduser, which is the wrong way to go about things imo.

I'm always happy to cooperate with downstream consumers of alacritty_terminal, but this just doesn't seem like the right way to go about this feature. If you want to try a different approach, feel free to open a new PR.

**Pull request closed without merging**
