### PR TITLE
Create srgb gl context by default

### PR DESCRIPTION
**Pull request by kchibisov**
For reference https://github.com/alacritty/alacritty/issues/4939 and
https://github.com/alacritty/alacritty/issues/3756.

### CODE REVIEW

**Comment by kchibisov** [comment]
I think the major problem is that we can't check for available pixel formats before hand.

**Comment by chrisduerr** [comment]
I don't remember, but didn't we do it this way around because one was supposed to be superior while the other would always work? If we put the one that always works first, the other one won't ever be triggered, right?

**Comment by kchibisov** [comment]
It does get triggered on intel or amd on Windows, since it doesn't have non-srgb or so. I haven't found a reference that it was other way around. It was always like that.

**Review by chrisduerr — COMMENTED** [review]
Does this completely fix the mentioned issues? If so we should add a changelog entry.

**Comment by kchibisov** [comment]
>Does this completely fix the mentioned issues? If so we should add a changelog entry.

I think it would make sense if fix it completely and not pick better default? Though, we can add a note that we prefer srgb surfaces now.

**Comment by chrisduerr** [comment]
> Though, we can add a note that we prefer srgb surfaces now.

I'm not sure people will know what that means, especially without pointing out the alternative? Should probably put it in a way the user can understand it.

**Comment by kchibisov** [comment]
I've verified that it does work on macOS. The fallback is a bit nicer than the chain we had before, and should also accelerate window creation in multiwindow context, given that probing done only ones.

**Review by chrisduerr — APPROVED** [review]

**Pull request merged**
