### PR TITLE
Symbol Font (with ranges) with fallback font support

### PR DESCRIPTION
**Pull request by sharkusk**
This is a slightly less useless pull request (compared to #6663) that allows a user to use a symbol font and configure specific ranges which will be used to override the main font.  Independently, a fallback font can be configured to bring a small amount of joy to the life of MacOS and Windows users.  This is a step towards the full font refactor proposal from #957.

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
How exactly is it a fallback font when it overrides the main font?

None of these PRs have anything to do with #957.

**Comment by sharkusk** [comment]
> How exactly is it a fallback font when it overrides the main font?
> 
> None of these PRs have anything to do with #957.

There are two additional font types added by this pull request:

**symbol** 
This overrides the main font based on ranges specified by the user

**fallback**
This font is checked after all other options have been exhausted.

See config file comments for specific details:

```
  # Fallback font used for glphs that cannot be found in normal font
   #fallback:
     # Font family
     #
     # If the fallback family is not specified, it will fall back to the
     # value specified for the normal font.
     #family: Symbols Nerd Font Mono
     #style: 2048-em

   # The symbol font will be used for the specified code ranges and checked
   # before the normal font.  Order of glyph checks are as follows:
   # built-in box drawing (if enabled), symbol (for given ranges), normal, fallback
   #symbol:
     # Please note: this is a sample configuration well suited for using Nerd Fonts.
     # If not specified, the default font will the normal font and the default
     # ranges are [[0,0],] (i.e. ignored.).
     # Due to glyph caching, changes to ranges requires alacritty to be restarted
     # before they take effect.
     #family: Symbols Nerd Font Mono
     #style: 2048-em
     #ranges: [[0x23fb, 0x23ff], [0x2665, 0x2666], [0x26a1, 0x26a2], [0x2b58, 0x2b59], [0xe000, 0xe00b], [0xe0a0, 0xe0a4], [0xe0b0, 0xe0c9], [0xe0ca, 0xe0cb], [0xe0cc, 0xe0d5], [0xe200, 0xe2aa], [0xe300, 0xe3ec], [0xe5fa, 0xe632], [0xe700, 0xe7c6], [0xea60, 0xebec], [0xf000, 0xf2e1], [0xf300, 0xf330], [0xf400, 0xf4aa], [0xf500, 0xfd47],]
```

**Comment by chrisduerr** [comment]
Yes, so you're adding a hacky solution to work around some issues which is completely unrelated to the original suggested implementation.

I'd be happy to look at any serious PRs trying to implement #957 but you're just wasting everyone's time throwing up some lazy solutions.

**Comment by sharkusk** [comment]
> Yes, so you're adding a hacky solution to work around some issues which is completely unrelated to the original suggested implementation.
> 
> 
> 
> I'd be happy to look at any serious PRs trying to implement #957 but you're just wasting everyone's time throwing up some lazy solutions.

Unfortunately as someone who has no previous experience with rust, tackling the complete refactor of the font system would very likely continue to be a waste of everyone's time.

I wish you the best and thanks for your continued work on alacritty. Happy trails.

**Comment by chrisduerr** [comment]
> Unfortunately as someone who has no previous experience with rust, tackling the complete refactor of the font system would very likely continue to be a waste of everyone's time.

That sounds about right and is why I wouldn't suggest #957 as a good first issue to anyone.

**Comment by illogic-al** [comment]
> > Unfortunately as someone who has no previous experience with rust, tackling the complete refactor of the font system would very likely continue to be a waste of everyone's time.
> 
> That sounds about right and is why I wouldn't suggest #957 as a good first issue to anyone.

And so that justifies you being a dick and alienating people who wanted, and tried to contribute?
I'm fairly certain from these reviews that I would not like working with you so I'll save both you and me the pain and not look into this any further. So that's two contributors now you've alienated. 👌🏾

**Pull request closed without merging**
