### PR TITLE
Initial implementation for #3245. Implement basic menu.

### PR DESCRIPTION
**Pull request by marcingrabda**
I have added a basic menu using 'muda' library and am requesting feedback for these changes. I also need some pointers on how I could somehow reuse existing CreateNewWindow and CreateNewTab actions from the newly added 'menu.rs'.

The 'muda' library is cross-platform, so it should work everywhere, but I have tested it so far only on macOS. At the moment this only adds one sub-menu called 'Shell' with 'New Window' and 'New Tab' items, but more can be added quite easily later.

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
This implementation makes no sense and I'm not interested in stepping you through implementing this feature myself.

**Comment by marcingrabda** [comment]
Do you mind providing any feedback at all? I don't mind learning from a failure. Muda seems to integrate well with winit and the implementation followed its tutorials. Alacritty is a decent terminal, but its integration with macOS is pretty crappy, which is something I was trying to improve.

**Comment by chrisduerr** [comment]
Using a crate at all is not an option and I don't see how you'd go and write a patch that calls GTK code without realizing you're running in the wrong direction…

**Comment by nixpulvis** [comment]
@chrisduerr why is any crate not an option here? I would think cross platform menu handling would make for a very nice crate. Now I’ve never used `muda` so I can’t really speak to this PR, I’m just surprised to hear this stance from you.

**Comment by chrisduerr** [comment]
> I would think cross platform menu handling would make for a very nice crate.

What cross-platform menu handling? That isn't even what Alacritty needs. We're looking for macOS menu handling.

**Pull request closed without merging**
