### PR TITLE
Fix cursor contrast for static cursor colors

### LINKED ISSUE #4576: How to change the cursor color when selecting text in TMUX?
I've been trying Alacritty for about a year now, and in the last couple of months noticed a change in the way text selection looks while in TMUX. For some reason, the last character does not appear to get selected (although it clearly is as it's being copied to my clipboard).

I can't narrow down if it's an issue with Alacritty or TMUX or both, and as such, I've also posted this issue in TMUX: https://github.com/tmux/tmux/issues/2504

I'm attaching a screenshot to demonstrate the problem:

Kapture 2020-12-15 at 21 29 56

Also, my `alacritty.yml` file:

```
window:
  startup_mode: SimpleFullscreen
  decorations: none
  padding:
    x: 5
    y: 0

font:
  size: 14
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic
  offset:
    x: 0
    y: 3

  use_thin_strokes: true

colors:
 # Default Colors
 primary:
   background: '#212121'
   foreground: '#f1f1f1'
 # Normal colors
 normal:
   black:   '#212121'
   red:     '#c30771'
   green:   '#10a778'
   yellow:  '#a89c14'
   blue:    '#008ec4'
   magenta: '#523c79'
   cyan:    '#20a5ba'
   white:   '#f1f1f1'
 # Bright colors
 bright:
   black:   '#424242'
   red:     '#e32791'
   green:   '#5fd7a7'
   yellow:  '#f3e430'
   blue:    '#b6d6fd'
   magenta: '#6855de'
   cyan:    '#4fb8cc'
   white:   '#ffffff'

 cursor:
   text: '#f3f3f3'
   cursor: '#1ac7fc'

# background_opacity: 0.99

bell:
  duration: 10
  color: '#626262'

# Use `xxd -psd` to discover other chars hex values
key_bindings:
  - { key: H,         mods: Alt,        chars: "\x1b\x68" }
  - { key: J,         mods: Alt,        chars: "\x1b\x6a" }
  - { key: K,         mods: Alt,        chars: "\x1b\x6b" }
  - { key: K,         mods: Command,    chars: "\x1C"     } # See .tmux.conf
  - { key: L,         mods: Alt,        chars: "\x1b\x6c" }
  - { key: O,         mods: Alt,        chars: "\x1b\x6f" }
  - { key: R,         mods: Shift|Alt,  chars: "\x1b\x52" }
  - { key: R,         mods: Alt,        chars: "\x1b\x72" }
  - { key: S,         mods: Alt,        chars: "\x1b\x73" }
  - { key: T,         mods: Alt,        chars: "\x1b\x74" }
  - { key: W,         mods: Alt,        chars: "\x1b\x77" }
  - { key: Backslash, mods: Shift|Alt,  chars: "\x1b\x7c" }
  - { key: Minus,     mods: Shift|Alt,  chars: "\x1b\x5f" }
  - { key: LBracket,  mods: Alt,        chars: "\x1b\x5b" }
  - { key: RBracket,  mods: Alt,        chars: "\x1b\x5d" }
  - { key: Semicolon, mods: Shift|Alt,  chars: "\x1b\x3a" }
  - { key: Slash,     mods: Alt,        chars: "\x1b\x2f" }

  - {
      key: N,
      mods: Command,
      command: {
        program: "open",
        args: ["-n", "/Applications/Alacritty.app"]
      }
    }

  - {
      key: Return,
      mods: Command,
      action: ToggleSimpleFullscreen
    }
```

Any ideas on why this might be happening?

### System

OS: macOS
Version: `alacritty 0.6.0 (04cbf76)`

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

I've run `alacritty -vv` and here is the output:

```
[2020-12-15 23:36:09.985459000] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8
[2020-12-15 23:36:09.985630000] [INFO ] [alacritty] Welcome to Alacritty
[2020-12-15 23:36:09.985659000] [INFO ] [alacritty] Configuration files loaded from:
[2020-12-15 23:36:09.985682000] [INFO ] [alacritty]   "/Users/nathan/.config/alacritty/alacritty.yml"
[2020-12-15 23:36:10.031411000] [DEBUG] [alacritty] Estimated DPR: 2
[2020-12-15 23:36:10.031481000] [DEBUG] [alacritty] Estimated window size: None
[2020-12-15 23:36:10.031505000] [DEBUG] [alacritty] Estimated cell size: 16 x 36
[2020-12-15 23:36:11.940867000] [INFO ] [alacritty] Device pixel ratio: 2
[2020-12-15 23:36:11.944234000] [INFO ] [alacritty] Initializing glyph cache...
[2020-12-15 23:36:11.968848000] [INFO ] [alacritty] ... finished initializing glyph cache in 0.02446039s
[2020-12-15 23:36:11.968967000] [INFO ] [alacritty] Cell size: 16 x 36
[2020-12-15 23:36:11.969006000] [INFO ] [alacritty] Padding: 10 x 0
[2020-12-15 23:36:11.969033000] [INFO ] [alacritty] Width: 1600, Height: 1200
[2020-12-15 23:36:11.993743000] [INFO ] [alacritty] PTY dimensions: Line(33) x Column(98)
[2020-12-15 23:36:11.997431000] [INFO ] [alacritty] Initialisation complete
[2020-12-15 23:36:12.026676000] [DEBUG] [alacritty_terminal] New num_cols is 190 and num_lines is 53
[2020-12-15 23:36:12.029329000] [INFO ] [alacritty] Padding: 10 x 0
[2020-12-15 23:36:12.029409000] [INFO ] [alacritty] Width: 3072, Height: 1920
```

### PR DESCRIPTION
**Pull request by chrisduerr**
Fixes #4576.

### CODE REVIEW

**Review by kchibisov — CHANGES_REQUESTED** [review]
The logic to invert cursor doesn't work at all anymore, since the cursor of color #ffffff doesn't get inverted on #ffffff background.

**Comment by chrisduerr** [comment]
> The logic to invert cursor doesn't work at all anymore, since the cursor of color #ffffff doesn't get inverted on #ffffff background.

With inversion or with both colors fixed?

**Comment by kchibisov** [comment]
With inversion.

**Comment by chrisduerr** [comment]
This is useless.

**Pull request closed without merging**
