### PR TITLE
Try new VTE branch for benchmarks

### PR DESCRIPTION
**Pull request by boazy**
See https://github.com/alacritty/vte/pull/115

### CODE REVIEW

**Comment by chrisduerr** [comment]
@perfbot

**Comment by chrisduerr** [comment]
@perfbot Second test because dense_cells is usually pretty stable and there seems to be an uptick.

**Comment by kchibisov** [comment]
could also be just regular noise due to how optimization went, IIRC it's quite common for spike like that and it was numerous times in the past.

**Comment by kchibisov** [comment]
@chrisduerr btw, which rust version was old or it's the same for both new/old, since before bot was writing the version/etc?

**Comment by chrisduerr** [comment]
> could also be just regular noise due to how optimization went, IIRC it's quite common for spike like that and it was numerous times in the past.

Yeah that's why I just ran it again.

> which rust version was old or it's the same for both new/old, since before bot was writing the version/etc?

It's the same Rust version, but it hasn't been updated in a while so I'll try that just to make sure.

**Comment by chrisduerr** [comment]
@perfbot Let's try again with 1.80.0.

**Comment by chrisduerr** [comment]
Seems fine in the latest results.

**Comment by chrisduerr** [comment]
Pretty sure I can still request stuff on closed PRs and there's no intention of upstreaming, so closing this PR.
Just let me know in a comment here if you want another benchmark run.

**Comment by chrisduerr** [comment]
@perfbot can you give this another go please?

**Comment by kchibisov** [comment]
Look a bit noisy, I'd say, but not sure it's a PR issue.

**Comment by kchibisov** [comment]
Maybe local rebench needed or maybe rust codegen is weird.

**Comment by chrisduerr** [comment]
I can update rust version and see what happens.

**Comment by chrisduerr** [comment]
@perfbot and one more time.

**Comment by chrisduerr** [comment]
Hm, all three results did show at least increased deviation for the dense cell benchmark. However within margin so it's tough to classify them as conclusive.

The comparison run against master (https://github.com/alacritty/alacritty/pull/8252#issuecomment-2427495284) did not exhibit these differences, instead it arguably shows the opposite trend.

**Comment by chrisduerr** [comment]
@perfbot going to try it one more time, just to make sure we have a good sample size.

**Comment by chrisduerr** [comment]
So 6/7 of the tests in this thread indicate fluctuations in dense cells. So I'm not confident the VTE patch is acceptable as-is.

**Pull request closed without merging**
