### PR TITLE
Add fontkit as a render backend

### PR DESCRIPTION
**Pull request by zacps**
Currently this just re-implements the `Rasterizer` trait that the existing backends use, but it might make more sense to refactor this to properly take advantage of more advanced features (like ligatures).

~~It also has some windows specific code, but that should be simple to remove.~~

Fixes https://github.com/jwilm/alacritty/issues/1568

### CODE REVIEW

**Comment by chrisduerr** [comment]
I've resolved all build errors on linux but it still had issues with crashes at runtime. It will probably need more than just a quick 5 minute fix-up to resolve the remaining macos problem, so it'll probably take a while until I can get to it.

Of course if someone else wants to look into making this work on Linux, support is always appreciated.

**Comment by zacps** [comment]
@chrisduerr This is pretty much done on the windows side, and I've switched to a fork of font-kit that *should* fix errors on linux. Could you give it another try?

Also is there anyone active for osx dev I can ping to get some testing there?

**Comment by sodiumjoe** [comment]
@chrisduerr sorry for the slow reply, I'd be happy to test. Anything specific I should be looking at?

**Comment by sodiumjoe** [comment]
just did a `cargo run` and it seems to build and run just fine

**Comment by sodiumjoe** [comment]
```
warning: unused `#[macro_use]` import
  --> font/src/lib.rs:49:26
   |
49 | #[cfg_attr(not(windows), macro_use)]
   |                          ^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

warning: unused import: `font_kit::canvas::RasterizationOptions`
  --> font/src/lib.rs:69:5
   |
69 | use font_kit::canvas::RasterizationOptions;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0277]: the trait bound `font_kit::canvas::RasterizationOptions: std::convert::From<RasterizationMethod>` is not satisfied
   --> font/src/fontkit/mod.rs:136:47
    |
136 |             self.options.rasterization_method.into()
    |                                               ^^^^ the trait `std::convert::From<RasterizationMethod>` is not implemented for `font_kit::canvas::RasterizationOptions`
    |
    = note: required because of the requirements on the impl of `std::convert::Into<font_kit::canvas::RasterizationOptions>` for `RasterizationMethod`

warning: unused import: `font_kit::canvas::RasterizationOptions`
  --> font/src/lib.rs:69:5
   |
69 | use font_kit::canvas::RasterizationOptions;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0277]: the trait bound `font_kit::canvas::RasterizationOptions: std::convert::From<RasterizationMethod>` is not satisfied
   --> font/src/fontkit/mod.rs:136:47
    |
136 |             self.options.rasterization_method.into()
    |                                               ^^^^ the trait `std::convert::From<RasterizationMethod>` is not implemented for `font_kit::canvas::RasterizationOptions`
    |
    = note: required because of the requirements on the impl of `std::convert::Into<font_kit::canvas::RasterizationOptions>` for `RasterizationMethod`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `font`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by TheDecryptor** [comment]
It runs ok, but the metrics and sizing is all wrong on a high DPI system.

screen shot 2018-12-22 at 3 17 40 pm

That's without any `style` attributes set in the config, just the base family.

**Comment by chrisduerr** [comment]
Thanks for the feedback. Looks like it runs on all systems then, but the metrics are messed up at least on Linux and macOS. Should be possible to get that fixed reasonably quickly hopefully.

**Comment by benpye** [comment]
Hey, @zacps I've been trying Alacritty on Windows but the lack of hinting is somewhat annoying on my desktop machine. What needs doing to get this PR merged?

**Comment by BYK** [comment]
Happy to give this a hand, including merge help :)

**Pull request closed without merging**
