### PR TITLE
Fix config TOCTOU

### PR DESCRIPTION
**Pull request by mattfbacon**
There is a TOCTOU because we explicitly check if the file exists before reading it. We should just check for a "not found" error from the read, instead.

### CODE REVIEW

**Comment by chrisduerr** [comment]
Have you actually been able to reproduce this in practice?

**Comment by mattfbacon** [comment]
WDYM, is the problem not self-apparent?

**Comment by chrisduerr** [comment]
> WDYM, is the problem not self-apparent?

I'm curious about the motivation behind this pull request. If it's just a theoretical issue that is fine, however I'd like to be aware if this actually caused real-world issues.

**Comment by mattfbacon** [comment]
It is primarily a theoretical issue, but it could have a real effect, because presumably the "not found" case was special-cased for a reason, to print a better error message, and that code path could be missed if the TOCTOU mismatch occurs.

**Review by chrisduerr — APPROVED** [review]

**Pull request merged**
