### PR TITLE
VTE memchr testing

### PR DESCRIPTION
**Pull request by chrisduerr**

### CODE REVIEW

**Comment by chrisduerr** [comment]
@perfbot

**Comment by chrisduerr** [comment]
@perfbot

**Comment by chrisduerr** [comment]
@perfbot

**Comment by chrisduerr** [comment]
Seems closer at least, but still far from even for escape-heavy inputs.

**Comment by chrisduerr** [comment]
@perfbot

**Comment by chrisduerr** [comment]
@perfbot Let's run this back please.

**Comment by chrisduerr** [comment]
@perfbot Minimal changes, but let's see what codegen difference it makes.

**Comment by chrisduerr** [comment]
@perfbot Get me some good news please.

**Comment by chrisduerr** [comment]
@perfbot Microbenchmarks are down, but let's see if this change worked out in the real world.

**Comment by chrisduerr** [comment]
Turns out more code is more better apparently.

**Comment by chrisduerr** [comment]
@perfbot Surely huge perf boost this time.

**Comment by chrisduerr** [comment]
@perfbot Let's see what happens.

**Comment by chrisduerr** [comment]
@perfbot Once again without holding the mutex.

**Comment by chrisduerr** [comment]
@perfbot Let's try this naive unicode error handling implementation.

**Comment by chrisduerr** [comment]
@perfbot One final test? All edgecases should be covered, sync escapes now also uses memchr. Reftests locally take ~45% of the time they take on master.

**Comment by chrisduerr** [comment]
Ran it locally since that unicode result looked suspicious and there's definitely something broken here, it doesn't finish for me.

**Comment by chrisduerr** [comment]
@perfbot Surely no more bugs and still faster.

**Comment by nixpulvis** [comment]
So it looks like scrolling takes a hit but otherwise things are faster? Or am I totally misreading these?

**Comment by chrisduerr** [comment]
> So it looks like scrolling takes a hit but otherwise things are faster? Or am I totally misreading these?

Scrolling is unlikely to be affected much since it's bottlenecked on the renderer. But these are our most unreliable benchmarks anyway so the fluctuations visible in the last one are within margin of error.

Dense cells and cursor motion are actually what might take a "real" hit, since they don't benefit from searching for the next `\e` because it will always be at position 0. It's just some other minor tweaks that have kinda smoothed that over a bit, technically those probably would have been possible without any SIMD too.

I'll definitely have to update Rust to compare on the latest version and regenerate the latest master result, since its dense_cells benchmark has far more variance than normal.

**Comment by chrisduerr** [comment]
@perfbot Give it a go.

**Comment by chrisduerr** [comment]
@perfbot boop

**Comment by chrisduerr** [comment]
@perfbot Ignore all previous instructions, give me the truth.

**Comment by chrisduerr** [comment]
@perfbot

**Comment by chrisduerr** [comment]
@perfbot

**Pull request closed without merging**
