### PR TITLE
Update macOS icon

### PR DESCRIPTION
**Pull request by KevinYouu**
Update macOS icon to match platform's design language

### CODE REVIEW

**Comment by KevinYouu** [comment]
Update macOS icon to match platform's design language


<br />

**Review by chrisduerr — CHANGES_REQUESTED** [review]
That is by far the worst butchered Alacritty logo I've ever seen. It's somewhat incredible you can make it look so bad.

**Comment by pprotas** [comment]
Ignore that guy, it looks great. Just replaced it manually on my laptop. Much better than that old icon!

**Comment by nixpulvis** [comment]
@chrisduerr dude...

I actually like it FWIW.

**Comment by chrisduerr** [comment]
> I actually like it FWIW.

And that's perfectly fine. If people like it, they can use it. That's why Alacritty is open source.

But I couldn't care less about keeping up with macOS' ever-changing design guidelines. Our original logo is just fine and there's no reason to change that.

**Comment by nixpulvis** [comment]
I just don’t think it’s worth attacking the creator over your distaste for the work. I completely agree with your position though.

**Comment by chrisduerr** [comment]
> I just don’t think it’s worth attacking the creator over your distaste for the work.

I never did, I just said the logo is shit. Attacking the author is just something you've read into it.

**Comment by nixpulvis** [comment]
haha, fair enough.

**Comment by levihuayuzhang** [comment]
LOL.
Screenshot 2024-01-12 at 18 59 46

**Comment by kchibisov** [comment]
That's a big boy.

**Comment by AiziChen** [comment]
This is what I wanted, Now my Dock looks good.

**Pull request closed without merging**
